import Vue from 'vue';

declare module 'vue-feather-icon' {
  export function install(): void;
  export class Activity {}
  export class Airplay {}
  export class AlertCircle {}
  export class AlertOctagon {}
  export class AlertTriangle {}
  export class AlignCenter {}
  export class AlignJustify {}
  export class AlignLeft {}
  export class AlignRight {}
  export class Anchor {}
  export class Aperture {}
  export class Archive {}
  export class ArrowDownCircle {}
  export class ArrowDownLeft {}
  export class ArrowDownRight {}
  export class ArrowDown {}
  export class ArrowLeftCircle {}
  export class ArrowLeft {}
  export class ArrowRightCircle {}
  export class ArrowRight {}
  export class ArrowUpCircle {}
  export class ArrowUpLeft {}
  export class ArrowUpRight {}
  export class ArrowUp {}
  export class AtSign {}
  export class Award {}
  export class BarChart2 {}
  export class BarChart {}
  export class BatteryCharging {}
  export class Battery {}
  export class BellOff {}
  export class Bell {}
  export class Bluetooth {}
  export class Bold {}
  export class BookOpen {}
  export class Book {}
  export class Bookmark {}
  export class Box {}
  export class Briefcase {}
  export class Calendar {}
  export class CameraOff {}
  export class Camera {}
  export class Cast {}
  export class CheckCircle {}
  export class CheckSquare {}
  export class Check {}
  export class ChevronDown {}
  export class ChevronLeft {}
  export class ChevronRight {}
  export class ChevronUp {}
  export class ChevronsDown {}
  export class ChevronsLeft {}
  export class ChevronsRight {}
  export class ChevronsUp {}
  export class Chrome {}
  export class Circle {}
  export class Clipboard {}
  export class Clock {}
  export class CloudDrizzle {}
  export class CloudLightning {}
  export class CloudOff {}
  export class CloudRain {}
  export class CloudSnow {}
  export class Cloud {}
  export class Code {}
  export class Codepen {}
  export class Command {}
  export class Compass {}
  export class Copy {}
  export class CornerDownLeft {}
  export class CornerDownRight {}
  export class CornerLeftDown {}
  export class CornerLeftUp {}
  export class CornerRightDown {}
  export class CornerRightUp {}
  export class CornerUpLeft {}
  export class CornerUpRight {}
  export class Cpu {}
  export class CreditCard {}
  export class Crop {}
  export class Crosshair {}
  export class Database {}
  export class Delete {}
  export class Disc {}
  export class DollarSign {}
  export class DownloadCloud {}
  export class Download {}
  export class Droplet {}
  export class Edit2 {}
  export class Edit3 {}
  export class Edit {}
  export class ExternalLink {}
  export class EyeOff {}
  export class Eye {}
  export class Facebook {}
  export class FastForward {}
  export class Feather {}
  export class FileMinus {}
  export class FilePlus {}
  export class FileText {}
  export class File {}
  export class Film {}
  export class Filter {}
  export class Flag {}
  export class FolderMinus {}
  export class FolderPlus {}
  export class Folder {}
  export class Gift {}
  export class GitBranch {}
  export class GitCommit {}
  export class GitMerge {}
  export class GitPullRequest {}
  export class Github {}
  export class Gitlab {}
  export class Globe {}
  export class Grid {}
  export class HardDrive {}
  export class Hash {}
  export class Headphones {}
  export class Heart {}
  export class HelpCircle {}
  export class Home {}
  export class Image {}
  export class Inbox {}
  export class Info {}
  export class Instagram {}
  export class Italic {}
  export class Layers {}
  export class Layout {}
  export class LifeBuoy {}
  export class Link2 {}
  export class Link {}
  export class Linkedin {}
  export class List {}
  export class Loader {}
  export class Lock {}
  export class LogIn {}
  export class LogOut {}
  export class Mail {}
  export class MapPin {}
  export class Map {}
  export class Maximize2 {}
  export class Maximize {}
  export class Menu {}
  export class MessageCircle {}
  export class MessageSquare {}
  export class MicOff {}
  export class Mic {}
  export class Minimize2 {}
  export class Minimize {}
  export class MinusCircle {}
  export class MinusSquare {}
  export class Minus {}
  export class Monitor {}
  export class Moon {}
  export class MoreHorizontal {}
  export class MoreVertical {}
  export class Move {}
  export class Music {}
  export class Navigation2 {}
  export class Navigation {}
  export class Octagon {}
  export class Package {}
  export class Paperclip {}
  export class PauseCircle {}
  export class Pause {}
  export class Percent {}
  export class PhoneCall {}
  export class PhoneForwarded {}
  export class PhoneIncoming {}
  export class PhoneMissed {}
  export class PhoneOff {}
  export class PhoneOutgoing {}
  export class Phone {}
  export class PieChart {}
  export class PlayCircle {}
  export class Play {}
  export class PlusCircle {}
  export class PlusSquare {}
  export class Plus {}
  export class Pocket {}
  export class Power {}
  export class Printer {}
  export class Radio {}
  export class RefreshCcw {}
  export class RefreshCw {}
  export class Repeat {}
  export class Rewind {}
  export class RotateCcw {}
  export class RotateCw {}
  export class Rss {}
  export class Save {}
  export class Scissors {}
  export class Search {}
  export class Send {}
  export class Server {}
  export class Settings {}
  export class Share2 {}
  export class Share {}
  export class ShieldOff {}
  export class Shield {}
  export class ShoppingBag {}
  export class ShoppingCart {}
  export class Shuffle {}
  export class Sidebar {}
  export class SkipBack {}
  export class SkipForward {}
  export class Slack {}
  export class Slash {}
  export class Sliders {}
  export class Smartphone {}
  export class Speaker {}
  export class Square {}
  export class Star {}
  export class StopCircle {}
  export class Sun {}
  export class Sunrise {}
  export class Sunset {}
  export class Tablet {}
  export class Tag {}
  export class Target {}
  export class Terminal {}
  export class Thermometer {}
  export class ThumbsDown {}
  export class ThumbsUp {}
  export class ToggleLeft {}
  export class ToggleRight {}
  export class Trash2 {}
  export class Trash {}
  export class TrendingDown {}
  export class TrendingUp {}
  export class Triangle {}
  export class Truck {}
  export class Tv {}
  export class Twitter {}
  export class Type {}
  export class Umbrella {}
  export class Underline {}
  export class Unlock {}
  export class UploadCloud {}
  export class Upload {}
  export class UserCheck {}
  export class UserMinus {}
  export class UserPlus {}
  export class UserX {}
  export class User {}
  export class Users {}
  export class VideoOff {}
  export class Video {}
  export class Voicemail {}
  export class Volume1 {}
  export class Volume2 {}
  export class VolumeX {}
  export class Volume {}
  export class Watch {}
  export class WifiOff {}
  export class Wifi {}
  export class Wind {}
  export class XCircle {}
  export class XSquare {}
  export class X {}
  export class Youtube {}
  export class ZapOff {}
  export class Zap {}
  export class ZoomIn {}
  export class ZoomOut {}
}